name: Daily-Commit-Bot

on:
  schedule:
    - cron: '0 18 * * *'
    
  workflow_dispatch:
  
  push:
      branches:
      - master

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: echo repository name
        run: echo "${{ github.repository }}"

      - name: repository checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: JunGyuRyu

      - name: Add date and push
        run: |
          cd JunGyuRyu
          date >> date.txt
          git add .
          git config --global user.email "qurrpdnjs1@naver.com"
          git config --global user.name "JunGyuRyu"
          git commit -am "Check Date"
          git push

